/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fho;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import java.awt.HeadlessException;
import java.sql.SQLException;
/**
 *
 * @author OmarA
 */
public class Randevular extends javax.swing.JFrame {

    
    public Randevular() {
        initComponents();
        DisplayRandevular();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        KayıtEtmek_Button = new javax.swing.JButton();
        Düzenlemek_Button = new javax.swing.JButton();
        Silmek_Button = new javax.swing.JButton();
        Geri_Button = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        Adi_Soyadı = new javax.swing.JTextField();
        TC_Numara = new javax.swing.JTextField();
        E_posta = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Muayene_Tarihi = new com.toedter.calendar.JDateChooser();
        Doktor_seçin = new javax.swing.JComboBox<>();

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 204));
        jLabel6.setText("Fırat Hastanesi");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        KayıtEtmek_Button.setBackground(new java.awt.Color(204, 204, 204));
        KayıtEtmek_Button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        KayıtEtmek_Button.setForeground(new java.awt.Color(0, 204, 204));
        KayıtEtmek_Button.setText("Kayıt Etmek");
        KayıtEtmek_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KayıtEtmek_ButtonMouseClicked(evt);
            }
        });

        Düzenlemek_Button.setBackground(new java.awt.Color(204, 204, 204));
        Düzenlemek_Button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Düzenlemek_Button.setForeground(new java.awt.Color(0, 204, 204));
        Düzenlemek_Button.setText("Düzenlemek");
        Düzenlemek_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Düzenlemek_ButtonMouseClicked(evt);
            }
        });

        Silmek_Button.setBackground(new java.awt.Color(204, 204, 204));
        Silmek_Button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Silmek_Button.setForeground(new java.awt.Color(0, 204, 204));
        Silmek_Button.setText("Silmek");
        Silmek_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Silmek_ButtonMouseClicked(evt);
            }
        });

        Geri_Button.setBackground(new java.awt.Color(204, 204, 204));
        Geri_Button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Geri_Button.setForeground(new java.awt.Color(0, 204, 204));
        Geri_Button.setText("Geri ");
        Geri_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Geri_ButtonMouseClicked(evt);
            }
        });
        Geri_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Geri_ButtonActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 204));
        jLabel7.setText("Randevular Listesi");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 204));
        jLabel8.setText("Adı-Soyadı");

        Adi_Soyadı.setBackground(new java.awt.Color(204, 204, 204));
        Adi_Soyadı.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Adi_Soyadı.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Adi_SoyadıActionPerformed(evt);
            }
        });

        TC_Numara.setBackground(new java.awt.Color(204, 204, 204));
        TC_Numara.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TC_Numara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TC_NumaraActionPerformed(evt);
            }
        });

        E_posta.setBackground(new java.awt.Color(204, 204, 204));
        E_posta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        E_posta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E_postaActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 204, 204));
        jLabel13.setText("E-posta");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 204, 204));
        jLabel14.setText("Muayene Tarihi");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 204, 204));
        jLabel15.setText("Doktor seçin");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 204, 204));
        jLabel16.setText("TC Numara");

        Doktor_seçin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dr. Halit", "Dr. Ali", "Dr. Hasan", "Dr. Mehmet", "Dr. Omer", "Dr. Recep ", "Dr. Melih" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(Adi_Soyadı, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(TC_Numara, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(E_posta, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(Muayene_Tarihi, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(Doktor_seçin, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Düzenlemek_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(KayıtEtmek_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Silmek_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Geri_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Muayene_Tarihi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Adi_Soyadı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TC_Numara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(E_posta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(KayıtEtmek_Button)
                                .addGap(33, 33, 33)
                                .addComponent(Düzenlemek_Button)
                                .addGap(27, 27, 27)
                                .addComponent(Silmek_Button)
                                .addGap(27, 27, 27)
                                .addComponent(Geri_Button))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(Doktor_seçin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     Connection Con = null;
    PreparedStatement Pst = null;
    ResultSet Rs = null,Rs1 = null;
    Statement St = null,St1 = null;
    
    private void DisplayRandevular(){
        try{
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/firat_hastanesi","root","");
           
            St  = Con.createStatement();
            
            Rs  = St.executeQuery("SELECT * FROM Randevular77");
            System.out.println(Rs);            
            jTable1.setModel(DbUtils.resultSetToTableModel(Rs));
        } catch (Exception e) {
                System.out.println(e.toString());
                }
        }
    int Id = 0;
    private void CountRandevular(){
        try{
            
            St1  = Con.createStatement();
            Rs1  = St1.executeQuery("SELECT Max(ID) FROM Randevular77");
            Rs1.next();
            Id = Rs1.getInt(1)+1;
            
        } catch (Exception e) {
                
                }
        }
    private void Clear(){
        Adi_Soyadı.setText("");
        TC_Numara.setText("");
        E_posta.setText("");
        
    }
    
      
    
    
    private void Adi_SoyadıActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Adi_SoyadıActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Adi_SoyadıActionPerformed

    private void TC_NumaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TC_NumaraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TC_NumaraActionPerformed

    private void E_postaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E_postaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E_postaActionPerformed

    private void Geri_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Geri_ButtonActionPerformed

    }//GEN-LAST:event_Geri_ButtonActionPerformed

    private void Geri_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Geri_ButtonMouseClicked
       new Home().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_Geri_ButtonMouseClicked

    private void KayıtEtmek_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KayıtEtmek_ButtonMouseClicked
       if(Adi_Soyadı.getText().isEmpty() || TC_Numara.getText().isEmpty() || E_posta.getText().isEmpty() || Doktor_seçin.getSelectedIndex() == -1 ) 
        {
            JOptionPane.showMessageDialog(this,"Eksik Bilgi Vardır");
        }else{
            try{
            
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/firat_hastanesi","root","");
            PreparedStatement Add = Con.prepareStatement("insert into Randevular77 values(?,?,?,?,?)");
            
            
            Add.setString(1, Adi_Soyadı.getText());
            Add.setString(2, TC_Numara.getText());
            Add.setString(3, E_posta.getText());
            Add.setString(4, Muayene_Tarihi.getDate().toString());
            Add.setString(5, Doktor_seçin.getSelectedItem().toString());
            
            int row = Add.executeUpdate();
            JOptionPane.showMessageDialog(this,"Randevu Kaydedildi");
            Con.close();
            DisplayRandevular();
            Clear();
        } catch (Exception e) {
                JOptionPane.showMessageDialog(this,e);
                }
    }            
    }//GEN-LAST:event_KayıtEtmek_ButtonMouseClicked

    String key = "";
    private void Silmek_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Silmek_ButtonMouseClicked
       if(key == ""){
            JOptionPane.showMessageDialog(this,"Bir Randevu Seçin Lütfen");
       }else{
           try{
              Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/firat_hastanesi","root","");
              String Query ="Delete from Randevular77 where Adi_Soyadı='"+key+"'";
              Statement Del = Con.createStatement();
              Del.executeUpdate(Query);
              JOptionPane.showMessageDialog(this,"Randevu Silindi");
              DisplayRandevular();
           } catch(Exception e){
               JOptionPane.showMessageDialog(this,e);
           }
               
           }
    }//GEN-LAST:event_Silmek_ButtonMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
       int MyIndex = jTable1.getSelectedRow();
       key = model.getValueAt(MyIndex, 0).toString();
       
       Adi_Soyadı.setText(model.getValueAt(MyIndex, 0).toString());
       TC_Numara.setText(model.getValueAt(MyIndex, 1).toString());
       E_posta.setText(model.getValueAt(MyIndex, 2).toString());
       Doktor_seçin.setSelectedItem(model.getValueAt(MyIndex, 4).toString());

       
    }//GEN-LAST:event_jTable1MouseClicked

    private void Düzenlemek_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Düzenlemek_ButtonMouseClicked
       if(key == ""){
            JOptionPane.showMessageDialog(this,"Bir Randevu Seçin Lütfen");
       }else{
           try{
              Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/firat_hastanesi","root","");
              String Query ="Update Randevular77 set TC_Numara = ?,E_posta = ?,Muayene_Tarihi =?,Doktor = ?  where Adi_Soyadi = ?";
              PreparedStatement Add = Con.prepareStatement(Query);
              
            Add.setString(5, key);
            Add.setString(1, TC_Numara.getText());
            Add.setString(2, E_posta.getText());
            Add.setString(3, Muayene_Tarihi.getDate().toString());
            
            Add.setString(4, Doktor_seçin.getSelectedItem().toString());
            
            int row = Add.executeUpdate();
              JOptionPane.showMessageDialog(this,"Randevu Güncellendi");
              Con.close();
              DisplayRandevular();
              Clear();
           } catch(Exception e){
               JOptionPane.showMessageDialog(this,e);
           }
               
           }
    }//GEN-LAST:event_Düzenlemek_ButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Randevular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Randevular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Randevular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Randevular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Randevular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Adi_Soyadı;
    private javax.swing.JComboBox<String> Doktor_seçin;
    private javax.swing.JButton Düzenlemek_Button;
    private javax.swing.JTextField E_posta;
    private javax.swing.JButton Geri_Button;
    private javax.swing.JButton KayıtEtmek_Button;
    private com.toedter.calendar.JDateChooser Muayene_Tarihi;
    private javax.swing.JButton Silmek_Button;
    private javax.swing.JTextField TC_Numara;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
